import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "../style.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <div className="logo">
            <img src="/images/logo.png" alt="logo" />
          </div>
          <ul>
            <li>
              <a className="active" href="#home">
                Home
              </a>
            </li>
            <li>
              <a href="#portfolio_section">Portfolio</a>
            </li>
            <li>
              <a href="#services">Services</a>
            </li>
            <li>
              <a href="#projects">Projects</a>
            </li>
            <li>
              <a href="successstory.html">Success stories</a>
            </li>
            <li>
              <a href="#contactus_section">Contact</a>
            </li>
          </ul>
          <div>
            <Link href="">ChatBot</Link>
            <Link className="get-started" href="/login">
              Get Started
            </Link>
          </div>
          <img src="/images/menu.png" className="menu" alt="menu" />
        </nav>
        {children}
      </body>
    </html>
  );
}
